flowgraph:
  r-htmlPath:
    - $
  r-jspPath:
    - $
  r-jspPath-in-func:
    - $
  r-htmlPath-in-func:
    - $
  r-viewPathHtml:
    - $
  r-viewPathJsp:
    - $
  r-setAttr:
    - r-htmlPath
    - r-viewPathHtml
    - r-htmlPath-in-func
  r-setAttrJsp:
    - r-jspPath
    - r-viewPathJsp
    - r-jspPath-in-func
  r-addAttr:
    - r-htmlPath
    - r-viewPathHtml
    - r-htmlPath-in-func
  r-addAttrJsp:
    - r-jspPath
    - r-viewPathJsp
    - r-jspPath-in-func
  r-global-model:
    - r-htmlPath
    - r-viewPathHtml
    - r-htmlPath-in-func
  r-global-model-jsp:
    - r-jspPath
    - r-viewPathJsp
    - r-jspPath-in-func
#  r-global-model-addAttr:
#    - r-htmlPath
  r-mav-htmlPath:
    - $
  r-mav-modelName:
    - r-mav-htmlPath
  r-mav-attr:
    - r-mav-modelName

rules:
  # model.addAttribute("name", ) <-> ${name}
  r-addAttr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/(&modelName).addAttribute'
      inline:
        identifier: (name)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name)}"

  r-addAttrJsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/(&modelName).addAttribute'
      inline:
        identifier: (name)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name)}"

  # model.addAttribute("name", ) <-> ${name}
  r-setAttr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/(&modelName).setAttribute'
      inline:
        identifier: (name)
    use:
      lang: HTML
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name)}"

  r-setAttrJsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/(&modelName).setAttribute'
      inline:
        identifier: (name)
    use:
      lang: HTML
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name)}"

  # functionName(Model modelName) <-> modelName.addAttribute("name", )
  # optional
#  r-modelName:
#    use:
#      lang: JAVA
#      file: (&javaFile).java
#      identifier: "(&functionName)/(modelName)"
#    def:
#      lang: JAVA
#      file: (&javaFile).java
#      identifier: (modelName)

  # return "htmlPath" <-> htmlPath.html
  # TODO 捕获组可以包含多个segment吗？
  r-htmlPath:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return
      inline:
        identifier: (htmlFile)
    def:
      lang: FILE
      file: (htmlFile...).html

  r-jspPath:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return
      inline:
        identifier: (jspFile)
    def:
      lang: FILE
      file: (jspFile...).jsp

  r-jspPath-in-func:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (jspFile)
    def:
      lang: FILE
      file: (jspFile...).jsp

  r-htmlPath-in-func:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return/**
      inline:
        identifier: (htmlFile)
    def:
      lang: FILE
      file: (htmlFile...).html

  r-viewPathHtml:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return
      inline:
        identifier: (htmlFile).html
    def:
      lang: FILE
      file: (htmlFile...).html

  r-viewPathJsp:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (functionName)/return
      inline:
        identifier: (jspFile).jsp
    def:
      lang: FILE
      file: (jspFile...).jsp

  # mav.setViewName("htmlPath") <-> htmlPath.html
  r-mav-htmlPath:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: '(mav).setViewName'
      inline:
        identifier: (htmlFile)
    def:
      lang: FILE
      file: (htmlFile...).html

  r-mav-htmlPath-jsp:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: '(mav).setViewName'
      inline:
        identifier: (jspFile)
    def:
      lang: FILE
      file: (jspFile...).jsp

  # functionName(ModelAndView mav) <-> mav.addObject("name", )
  # TODO
  r-mav-modelName:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: "(functionName)/(&mav)"
      varType: ModelAndView
    use:
      lang: JAVA
      file: (&javaFile).java
      identifier: (functionName)/(&mav).addObject
      inline:
        identifier: (name)

  # mav.addObject("name", ) <-> ${name}
  r-mav-attr:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&controller)/(&functionName)/(&mav)/addObject'
      inline:
        identifier: (&name)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(&name)}"

  # @ModelAttribute("name") <-> ${name}
  r-global-model:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name)
    use:
      lang: OTHER
      file: (&htmlFile).html
      identifier: "**"
      inline:
        identifier: "${(name)}"

  r-global-model-jsp:
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: '(&functionName)/@ModelAttribute'
      inline:
        identifier: (name)
    use:
      lang: OTHER
      file: (&jspFile).jsp
      identifier: "**"
      inline:
        identifier: "${(name)}"

  # @ModelAttribute & addAttribute("name") <-> ${name}
#  r-global-model-addAttr:
#    def:
#      lang: JAVA
#      file: (&javaFile).java
#      identifier: '(&controller)/(&globalModelFunc)[hasAnno="ModelAttribute"]/**/(&modelName)/addAttribute'
#      inline:
#        identifier: (name)
#    use:
#      lang: HTML
#      file: (&htmlFile).html
#      identifier: "**"
#      inline:
#        identifier: "${(name)}"