rules:
  - use:
      lang: Java
      file: "*.java"
      identifier: R.id.(name)
    def:
      lang: Xml
      file: "*.xml"
      identifier: "**"
      inline:
        identifier: '@+id\/(name)'

  - use:
      lang: Java
      file: "*.java"
      identifier: R.layout.(name)
    def:
      lang: Xml
      file: "(name).xml"
      identifier: ""
