rules:
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Select
      inline:
        identifier: "#{(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Insert
      inline:
        identifier: "#{(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Delete
      inline:
        identifier: "#{(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Update
      inline:
        identifier: "#{(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Select
      inline:
        identifier: "${(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Insert
      inline:
        identifier: "${(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Delete
      inline:
        identifier: "${(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Java
      file: '(filename).java'
      identifier: (method)/Update
      inline:
        identifier: "${(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "(filename).java"
      identifier: (method)/(name)
  - - protocol: any
      lang: Xml
      file: '*.xml'
      identifier: mapper/**
      inline:
        identifier: "#{(name),jdbcType=*}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "*.java"
      identifier: (name)
  - - protocol: any
      lang: Xml
      file: '*.xml'
      identifier: mapper/**
      inline:
        identifier: "#{(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "*.java"
      identifier: (name)
  - - protocol: any
      lang: Xml
      file: '*.xml'
      identifier: mapper/**
      inline:
        identifier: "${(name),jdbcType=*}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "*.java"
      identifier: (name)
  - - protocol: any
      lang: Xml
      file: '*.xml'
      identifier: mapper/**
      inline:
        identifier: "${(name)}"
        lang: Sql
    - protocol: def
      lang: Java
      file: "*.java"
      identifier: (name)
  - - protocol: any
      lang: Xml
      file: '*.xml'
      identifier: mapper/**
      inline:
        identifier: (name)
        lang: Sql
    - protocol: def
      lang: Java
      file: "*.java"
      identifier: (name)
