rules:
  - use:
      lang: Java
      file: '*.java'
      identifier: (namespace)Mapper/(method)
    def:
      lang: Xml
      file: "(namespace)Mapper.xml"
      identifier: id
      inline:
        identifier: '(method)'
