flowgraph:
  r-layout:
    - $
  r-menu:
    - $
  r-dataBindingClassLink:
    - $
  r-dataBindingClassLinkFallBack1:
    - $
  r-dataBindingClassLinkFallBack2:
    - $
  r-viewBindingClassLink:
    - $
  r-id:
    - r-layout
    - r-menu
    - r-dataBindingClassLink
    - $
  r-id-fallBack1:
    - r-dataBindingClassLinkFallBack1
  r-id-fallBack2:
    - r-dataBindingClassLinkFallBack2
  r-id-values:
    - $
#  r-dataBindingClass:
#    - $
  r-include-layout-dataBinding:
    - r-dataBindingClassLink
  r-include-layout-resource:
    - r-layout
  r-include-id:
    - r-include-layout-resource
#  r-include-android-id:
#    - r-include-layout-dataBinding
  r-include-dataBinding-widget:
    - r-include-layout-dataBinding
  r-dataBinding:
    - r-dataBindingClassLink
#    - $
  r-dataBindingFallBack1:
    - r-dataBindingClassLinkFallBack1
  r-dataBindingFallBack2:
    - r-dataBindingClassLinkFallBack2
  r-dataBinding-function:
    - r-dataBindingClassLink
    - r-dataBindingClassLinkFallBack1
    - r-dataBindingClassLinkFallBack2
  r-xml-inner:
    - $
  r-xml-inner-plus:
    - $
  r-xml-include-inner:
    - r-include-id
  r-xml-include-inter:
    - r-include-id

rules:
  # setContentView(R.layout.layoutName) <-> layoutName.xml
  r-layout:
    brokenType: MissingDef
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: R.layout.(layoutName)
    def:
      lang: XML
      file: layout/(layoutName).xml

  r-menu:
    brokenType: MissingDef
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: R.menu.(layoutName)
    def:
      lang: XML
      file: menu/(layoutName).xml

  # R.id.name <-> @+id
  r-id:
    brokenType: Either
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: R.id.(name:snake)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name:snake)'
  r-id-fallBack1:
    brokenType: Either
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&class)/(&inner)/**/R.id.(name:snake)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name:snake)'
  r-id-fallBack2:
    brokenType: Either
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&class)/**/R.id.(name:snake)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name:snake)'

  # R.id.name <-> @id
  r-id-values:
    brokenType: MissingDef
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: R.id.(name:snake)
    def:
      lang: XML
      file: res/values/*.xml
      identifier: item/name
      inline:
        identifier: '(name:snake)'

  # binding.setContentView(this, R.layout.layoutName) <-> layoutName.xml
  r-dataBindingLayout:
    brokenType: MissingDef
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: "(bindingVar)/setContentView/R.layout.(layoutName)"
    def:
      lang: XML
      file: '(layoutName).xml'

  r-dataBindingClassLink:
    brokenType: MissingDef
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (bindingVar)
      varType: (layoutName:pascal)Binding
    def:
      lang: XML
      file: (layoutName:snake).xml
  r-dataBindingClassLinkFallBack1:
    hidden: true
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: '(class)/(inner)/**/(layoutName:pascal)Binding'
    def:
      lang: XML
      file: (layoutName:snake).xml
  r-dataBindingClassLinkFallBack2:
    hidden: true
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: '(class)/**/(layoutName:pascal)Binding'
    def:
      lang: XML
      file: (layoutName:snake).xml
  r-viewBindingClassLink:
    hidden: true
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (bindingVar)
      varType: ViewBinding
    def:
      lang: JAVA
      file: (javaFile).java
      identifier: (bindingVar)
      varType: ViewBinding

  # binding.widgetId <-> @+id/widgetId
  r-dataBinding:
    brokenType: Either
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&bindingVar).(name:camel)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
  r-dataBindingFallBack1:
    hidden: true
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: '(&class)/(&inner)/**/*.(name:camel)'
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
  r-dataBindingFallBack2:
    hidden: true
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: '(&class)/**/*.(name:camel)'
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'

  r-dataBinding-function:
    hidden: true
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&bindingVar).*
      isFunc: true
    def:
      lang: JAVA
      file: (&javaFile).java
      identifier: (&bindingVar)

  r-include-layout-dataBinding:
    brokenType: MissingDef
    use:
      lang: XML
      file: (&layoutName).xml
      identifier: include/layout
      inline:
        identifier: '@layout\/(includeLayout)'
    def:
      lang: XML
      file: (includeLayout).xml

  r-include-layout-resource:
    brokenType: MissingDef
    use:
      lang: XML
      file: (&layoutName).xml
      identifier: include/layout
      inline:
        identifier: '@layout\/(includeLayout)'
    def:
      lang: XML
      file: (includeLayout).xml

  r-include-id:
    brokenType: Either
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: R.id.(name)
    def:
      lang: XML
      file: (&includeLayout).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'

#  r-include-dataBinding:
#    use:
#      lang: JAVA
#      file: '(&javaFile).java'
#      identifier: (&bindingVar).(name)
#    def:
#      lang: XML
#      file: (&includeLayout).xml
#      identifier: android:id
#      inline:
#        identifier: '@+id\/(name:snake)'

#  r-include-android-id:
#    hidden: true
#    use:
#      lang: XML
#      file: (&layoutName).xml
#      identifier: include/android:id
#      inline:
#        identifier: '@+id\/(includeId)'
#    def:
#      lang: XML
#      file: (&layoutName).xml
#      identifier: include/android:id
#      inline:
#        identifier: '@+id\/(includeId)'

  r-include-dataBinding-widget:
    brokenType: Either
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&bindingVar).(&includeId:camel).(name:camel)
    def:
      lang: XML
      file: (&includeLayout).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name:snake)'


  r-xml-inner:
    hidden: true
    def:
      lang: XML
      file: (layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
    use:
      lang: XML
      file: (layoutName).xml
      identifier: '**'
      inline:
        identifier: '@id\/(name)'
  r-xml-inner-plus:
    hidden: true
    def:
      lang: XML
      file: (layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
    use:
      lang: XML
      file: (layoutName).xml
      identifier: '*layout_*'
      inline:
        identifier: '@+id\/(name)'
  r-xml-include-inner:
    hidden: true
    def:
      lang: XML
      file: (&includeLayout).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
    use:
      lang: XML
      file: (&includeLayout).xml
      inline:
        identifier: '@id\/(&name)'
  r-xml-include-inter:
    hidden: true
    def:
      lang: XML
      file: (&includeLayout).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
    use:
      lang: XML
      file: (&layoutName).xml
      inline:
        identifier: '*\/(&name)'
