flowgraph:
  r-layout:
    - $
  r-id:
    - r-layout
    - $
  r-dataBindingClassLink:
    - $
  r-dataBinding:
    - r-dataBindingClassLink
    - r-layout
#    - $

rules:
  # setContentView(R.layout.layoutName) <-> layoutName.xml
  r-layout:
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: R.layout.(layoutName)
    def:
      lang: XML
      file: layout/(layoutName).xml

  r-menu:
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: R.menu.(layoutName)
    def:
      lang: XML
      file: menu/(layoutName).xml

  # R.id.name <-> @+id
  r-id:
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: R.id.(name)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'

  # <data class="bindingName"> <-> bindingName bindingVar
  r-dataBindingClass:
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: "(bindingVar)"
      varType: bindingName
    def:
      lang: XML
      file: '(layoutName).xml'
      identifier: data/class
      inline:
        identifier: (bindingName)

  # binding.setContentView(this, R.layout.layoutName) <-> layoutName.xml
  r-dataBindingLayout:
    use:
      lang: JAVA
      file: '(javaFile).java'
      identifier: "(bindingVar)/setContentView/R.layout.(layoutName)"
    def:
      lang: XML
      file: '(layoutName).xml'

  r-dataBindingClassLink:
    use:
      lang: JAVA
      file: (javaFile).java
      identifier: (bindingVar)
      varType: (layoutName:capitalized)Binding
    def:
      lang: XML
      file: (layoutName:snake).xml

  # binding.widgetId <-> @+id/widgetId
  r-dataBinding:
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&bindingVar).(widgetId)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(widgetId:snake)'
